### ISSUE TITLE
How to make a custom pages ?

### ISSUE THREAD

**Issue by afnizarnur** [codepolitanlab/pusakacms#19]
More specifically, I want to create a page that has a file css, js, and all assets required on that page without follow the theme.
Can pusakacms create like that?

**Comment by yllumi** [comment]
@flamekaizar, You can add some CSS and JS code immediately in page content to override main style. But if you want to use another assets different from default style, you can make a new layout i.e. yourtheme/views/layouts/_customlayout.php and use it in your page. Note that the custom layout file name must be prefixed with underscore in order to show in dropdown for choice layout in page panel.

**Comment by flamekaizar** [comment]
@yllumi I see, but it sounds difficult for me :sweat_smile:  
Are this cms has plugins to include assets directly into the page?

**Comment by yllumi** [comment]
Yes it has. But the documentation and manual is still in process of writing. But if you familiar with PHP and [Lex Parser](https://github.com/pyrocms/lex), you can open system/application/plugins/asset.php to see any asset plugin available to embed asset tag and URL into page content.
